universe = vanilla

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

executable = process_data_fast1.sh
arguments = $(state) 2023

transfer_input_files = process_data_fast1.sh, process_data_fast1.R, 2023/2023/$(state)-2023

output = logs/$(state)_2023.out
error = logs/$(state)_2023.err
log = logs/$(state)_2023.log

request_cpus = 1
request_memory = 1GB
request_disk = 8GB

queue state from states_queue.txt
