universe = vanilla

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

executable = process_data_fast1.sh
arguments = $(state) 2022

transfer_input_files = process_data_fast1.sh, process_data_fast1.R, 2022/2022/$(state)-2022

output = logs/$(state)_2022.out
error = logs/$(state)_2022.err
log = logs/$(state)_2022.log

request_cpus = 1
request_memory = 1GB
request_disk = 8GB

queue state from states_queue.txt
